[project]
name = "mittfortum"
version = "0.1.0"
description = "Home Assistant custom integration for Mittfortum"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PyJWT>=2.4.0",
    "httpx>=0.24.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=3.0.0",
    "ruff>=0.4.0",
    "pyrefly>=0.1.0",
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "homeassistant>=2025.1.0",
]

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
